In [1]:
#https://www.youtube.com/watch?v=uuhi830wOzs

#1. What are Python key features?

# Open Source
# OOP
# Easy to learn
# Easy to Debug
# Easy to integrate

In [19]:
#2. What are keywords in Python?

#33 basic keywords def, list, True, False, if, else, None, return, print...
import pandas as pd
dic = {
    'Keywords': ['True', 'False', 'for', 'while', 'break', 'continue','if', 'else', 'elif', 'finally', 'and', 'or', 'as', 'def', 'del',
                'except',]
}
dic


{'Keywords': ['True',
  'False',
  'for',
  'while',
  'break',
  'continue',
  'if',
  'else',
  'elif',
  'finally',
  'and',
  'or',
  'as',
  'def',
  'del',
  'except']}

In [20]:
KW_DF = pd.DataFrame.from_dict(dic)

In [26]:
#KW_DF
KW_DF.sort_values(by = 'Keywords')
#len(KW_DF)

Keywords
1      False
0       True
10       and
12        as
4      break
5   continue
13       def
14       del
8       elif
7       else
15    except
9    finally
2        for
6         if
11        or
3      while

In [3]:
#3. What are literals in Python?

# 4 types: 1. String literals ('Anything in quotes') 2. Numeric literals (Integers, Floats) 
#3. Boolean (True, False) 4. Special (None)

In [6]:
#4. How can you concatenate 2 tuples?

tup1 = (1, 2, 'String')
tup2 = (3, 4)
tup3 = tup1 + tup2

In [7]:
tup3

(1, 2, 'String', 3, 4)

In [15]:
#5. What are functions in Python?

#built-in (for ex. print) and user defined like the one below:

#Built-In Function

print('Happy')

Happy


In [16]:
#User defined function

def func(a, b):
    return (a+b)

func(2, 3)

5

In [28]:
#6. How can you initialize a 5X5 NumPy array with only zeros?

#NumPy has a funciton that does precisely this!


#Long way
import numpy as np
a = np.array(
    [
        (0, 0, 0, 0, 0), 
        (0, 0, 0, 0, 0), 
        (0, 0, 0, 0, 0), 
        (0, 0, 0, 0, 0), 
        (0, 0, 0, 0, 0)]
)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
five_zeros = np.zeros((5,5))

In [31]:
print(five_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
